[build]
publish = "dist" 
command = "npm run build"
functions = "netlify/functions"

# Redirect API requests to the serverless function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

# Redirect all other requests to the SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200